#include<iostream.h>
#include<conio.h>
int partition(int arr[],int low,int high)
{
   int pivot=arr[high];
   int i=low-1;
   for(int j=low;j<high;j++)
   {
       if(arr[j]<pivot)
       {
	  i++;
	  int temp=arr[i];
	  arr[i]=arr[j];
	  arr[j]=temp;
       }
   }
       i++;
       int temp=arr[i];
       arr[i]=arr[high];
       arr[high]=temp;
       return i;
}
void quickSort(int arr[],int low,int high)
{
    if(low<high)
    {
      int pidx=partition(arr,low,high);
      quickSort(arr,low,pidx-1);
      quickSort(arr,pidx+1,high);
    }
}
void print(int arr[],int n)
{
    for(int i=0;i<n;i++)
    {
       cout<<arr[i]<<" ";
    }
}
void main()
{
    int arr[]={6,3,9,5,2,8};
    int size=sizeof(arr)/sizeof(arr[0]);
    clrscr();
    cout<<"array befor quick sort =\n ";
    print(arr,size);
    quickSort(arr,0,size-1);
    cout<<"\narray after quick sort = \n";
    print(arr,size);
    getch();
}









































